CREATE TABLE users (
user_id INTEGER PRIMARY KEY AUTOINCREMENT,
username VARCHAR(25) UNIQUE NOT NULL,
password VARCHAR(25) NOT NULL
);

CREATE TABLE chats (
chat_id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(25) NOT NULL);

CREATE TABLE messages (
chat_id INTEGER NOT NULL,
user_id INTEGER NOT NULL,
content VARCHAR(255) NOT NULL,
announcement BOOL NOT NULL DEFAULT 0,
sent_time DATETIME NOT NULL,
FOREIGN KEY (chat_id) REFERENCES chats(chat_id) ON DELETE CASCADE,
FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE);
